### ISSUE TITLE
About cutoff for CSREP's differential score? 

### ISSUE THREAD

**Issue by xxbb23** [ernstlab/csrep#1]
Dear CSREP developer,
We get a CSREP's differential chromatin state map between two groups as follow.
We wonder what cutoff is better to define the chromatin states switch?
Another question:

When CSREP calculates differential chromatin state maps based on the probabilistic chromatin state map matrices for each group, is there a significance test of each 200bp bin ? If so, how do we get it?
please help me!

state_1 state_2 state_3 state_4 state_5 state_6 state_7 state_8 state_9 state_10        state_11        state_12
0       0.01170744949645206     0.00015902154331984755  0.0009705927200889826   7.702708036353723e-06   2.150157645998734e-06   1.1096675754637955e-05  -1.8702182926679444e-05 5.6234500850712115e-06  0.0010414806504337325   0.01654480578715283     -0.030531837462437594   0.00010061645639484156
1       0.01170744949645206     0.00015902154331984755  0.0009705927200889826   7.702708036353723e-06   2.150157645998734e-06   1.1096675754637955e-05  -1.8702182926679444e-05 5.6234500850712115e-06  0.0010414806504337325   0.01654480578715283     -0.030531837462437594   0.00010061645639484156
2       0.01170744949645206     0.00015902154331984755  0.0009705927200889826   7.702708036353723e-06   2.150157645998734e-06   1.1096675754637955e-05  -1.8702182926679444e-05 5.6234500850712115e-06  0.0010414806504337325  0.01654480578715283     -0.030531837462437594   0.00010061645639484156
3       0.01170744949645206     0.00015902154331984755  0.0009705927200889826   7.702708036353723e-06   2.150157645998734e-06   1.1096675754637955e-05  -1.8702182926679444e-05 5.6234500850712115e-06  0.0010414806504337325   0.01654480578715283     -0.030531837462437594   0.00010061645639484156
4       0.01170744949645206     0.00015902154331984755  0.0009705927200889826   7.702708036353723e-06   2.150157645998734e-06   1.1096675754637955e-05  -1.8702182926679444e-05 5.6234500850712115e-06  0.0010414806504337325   0.01654480578715283     -0.030531837462437594   0.00010061645639484156

**Comment by havu73** [comment]
Hi, Thank you for your questions! When we designed CSREP, we thought of doing a significance test for each bin of 200bp, using permutation test (each bin's observed CSREP score will be put against a distribution of CSREP's score of different permutations of samples from 2 groups). However, that idea was never practical because of the high computational cost. At the same time, I personally felt that in many cases, the values of summary chromatin state map is close to 0 or 1. Therefore, a chromatin state switch is quite easy to detect. I would personally recommend a cutoff of absolute values >= 0.5. Because, theoretically, it means that |P(group1 = s) - P(group2 =s)| >= 0.5 --> if P(group1=s) >0.5 then P(group2=s)< 0.5, I would consider that a chromatin state switch. We will keep thinking about this question to potentially come up with an efficient statistical test to declare chromatin state switch (without doing permutation and running CSREP multiple rounds). Thank you and let us know if that answers your question!

**Comment by xxbb23** [comment]
Thank you very much！ It helps me a lot.
